shell            zsh

font_family      JetBrainsMono Nerd Font
font_size        12.0
italic_font      auto

font_features JetBrainsMonoNF-Regular +calt +liga +dlig

window_padding_width 4
confirm_os_window_close 0
background_opacity 0.85
background_blur 1
background_color #cba6f7

# Tab Bar (Styling it like your Waybar)
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #313244

# Cursor & Mouse
cursor_shape block
shell_integration enabled no-cursor
mouse_hide_wait 3.0

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes
